exports.type = {
    '.txt': 'text/plain',
    '.png': 'image/png',
    '.gif': 'image/gif',
    '.html': 'text/html',
    '.pdf': 'application/pdf',
    '.ico': 'iamge/x-icon',
    '.js': 'text/javascript',
    '.css': 'text/css',
    '.avi': 'video/x-msvideo',
    '.mpeg': 'video/mpeg',
    '.ogv': 'video/ogg',
    '.webm': 'video/webm',
    '.flv': 'application/octet-stream',
    '.mp4': 'application/octet-stream',
}